backend:
  name: git-gateway
  repo: catiuespi/neacajui-v10
  branch: master 

media_folder: "static/images/uploads"
public_folder: "uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
